
def Colors():
  TEXT_RED = '\033[31m'
  TEXT_GREEN = '\033[32m'
  TEXT_YELLOW = '\033[33m'
  TEXT_RESET = '\033[0m'
  return TEXT_RED, TEXT_GREEN, TEXT_YELLOW, TEXT_RESET

TEXT_RED, TEXT_GREEN, TEXT_YELLOW, TEXT_RESET = Colors()
